sonar.projectKey=iuryhirabara-raizes
sonar.organization=iuryhirabara-raizes
sonar.projectName=Raízes do Nordeste
sonar.projectVersion=1.0.0

# Caminhos para fontes e testes
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js

# Configurações de análise do JavaScript
sonar.sourceEncoding=UTF-8

# Caminho para os relatórios de cobertura do Jest (LCOV)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
